<a href="https://colab.research.google.com/github/VivianeSouza923/Data-Analysis-Practices/blob/main/%20Association%20between%20Variables%20(Qualitative%20and%20Quantitative).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('/content/Companhia_MB.xlsx')
df

,N,Estado Civil,Grau de Instrução,N de Filhos,Salario (x Sal Min),Anos,Meses,Região de Procedência
0,1,solteiro,ensino fundamental,NaN,4.00,26,3,interior
1,2,casado,ensino fundamental,1.0,4.56,32,10,capital
2,3,casado,ensino fundamental,2.0,5.25,36,5,capital
3,4,solteiro,ensino médio,NaN,5.73,20,10,outra
4,5,solteiro,ensino fundamental,NaN,6.26,40,7,outra
5,6,casado,ensino fundamental,0.0,6.66,28,0,interior
6,7,solteiro,ensino fundamental,NaN,6.86,41,0,interior
7,8,solteiro,ensino fundamental,NaN,7.39,43,4,capital
8,9,casado,ensino médio,1.0,7.59,34,10,capital
9,10,solteiro,ensino médio,NaN,7.44,23,6,outra
10,11,casado,ensino médio,2.0,8.12,33,6,interior
11,12,solteiro,ensino fundamental,NaN,8.46,27,11,capital
12,13,solteiro,ensino médio,NaN,8.74,37,5,outra
13,14,casado,ensino fundamental,3.0,8.95,44,2,outra
14,15,casado,ensino médio,0.0,9.13,30,5,interior
15,16,solteiro,ensino médio,NaN,9.35,38,8,outra
16,17,casado,ensino médio,1.0,9.77,31,7,capital
17,18,casado,ensino fundamental,2.0,9.80,39,7,outra
18,19,solteiro,superior,NaN,10.53,25,8,interior
19,20,solteiro,ensino médio,NaN,10.76,37,4,interior
20,21,casado,ensino médio,1.0,11.06,30,9,outra
21,22,solteiro,ensino médio,NaN,11.59,34,2,capital
22,23,solteiro,ensino fundamental,NaN,12.00,41,0,outra
23,24,casado,superior,0.0,12.79,26,1,outra
24,25,casado,ensino médio,2.0,13.23,32,5,interior
25,26,casado,ensino médio,2.0,13.60,35,0,outra
26,27,solteiro,ensino fundamental,NaN,13.85,46,7,outra
27,28,casado,ensino médio,0.0,14.69,29,8,interior
28,29,casado,ensino médio,5.0,14.71,40,6,interior
29,30,casado,ensino médio,2.0,15.99,35,10,capital
30,31,solteiro,superior,NaN,16.22,31,5,outra
31,32,casado,ensino médio,1.0,16.61,36,4,interior
32,33,casado,superior,3.0,17.26,43,7,capital
33,34,solteiro,superior,NaN,18.75,33,7,capital
34,35,casado,ensino médio,2.0,19.40,48,11,capital
35,36,casado,superior,3.0,23.30,42,2,interior

In [3]:
# os dados (que são variáveis quantitativas) da coluna salário estão em formato string (quantitativa é só número!!!), portanto bvou fazer essa substituição.

sal = {
    '4,00':4.00,
    '4,56':4.56,
    '5,25':5.25,
    '5,73':5.73,
    '6,26':6.26,
    '6,66':6.66,
    '6,86':6.86,
    '7,39':7.39,
    '7,59':7.59,
    '7,44':7.44,
    '8,12':8.12,
    '8,46':8.46,
    '8,74':8.74,
    '8,95':8.95,
    '9,13':9.13,
    '9,35':9.35,
    '9,77':9.77,
    '9,80':9.80,
    '10,53':10.53,
    '10,76':10.76,
    '11,06':11.06,
    '11,59':11.59,
    '12,00':12.00,
    '12,79':12.79,
    '13,23':13.23,
    '13,60':13.60,
    '13,85':13.85,
    '14,69':14.69,
    '14,71':14.71,
    '15,99':15.99,
    '16,22':16.22,
    '16,61':16.61,
    '17,26':17.26,
    '18,75':18.75,
    '19,40':19.40,
    '23,30':23.30,

}

df['Salario (x Sal Min)'].replace(sal, inplace=True)
df

,N,Estado Civil,Grau de Instrução,N de Filhos,Salario (x Sal Min),Anos,Meses,Região de Procedência
0,1,solteiro,ensino fundamental,NaN,4.00,26,3,interior
1,2,casado,ensino fundamental,1.0,4.56,32,10,capital
2,3,casado,ensino fundamental,2.0,5.25,36,5,capital
3,4,solteiro,ensino médio,NaN,5.73,20,10,outra
4,5,solteiro,ensino fundamental,NaN,6.26,40,7,outra
5,6,casado,ensino fundamental,0.0,6.66,28,0,interior
6,7,solteiro,ensino fundamental,NaN,6.86,41,0,interior
7,8,solteiro,ensino fundamental,NaN,7.39,43,4,capital
8,9,casado,ensino médio,1.0,7.59,34,10,capital
9,10,solteiro,ensino médio,NaN,7.44,23,6,outra
10,11,casado,ensino médio,2.0,8.12,33,6,interior
11,12,solteiro,ensino fundamental,NaN,8.46,27,11,capital
12,13,solteiro,ensino médio,NaN,8.74,37,5,outra
13,14,casado,ensino fundamental,3.0,8.95,44,2,outra
14,15,casado,ensino médio,0.0,9.13,30,5,interior
15,16,solteiro,ensino médio,NaN,9.35,38,8,outra
16,17,casado,ensino médio,1.0,9.77,31,7,capital
17,18,casado,ensino fundamental,2.0,9.80,39,7,outra
18,19,solteiro,superior,NaN,10.53,25,8,interior
19,20,solteiro,ensino médio,NaN,10.76,37,4,interior
20,21,casado,ensino médio,1.0,11.06,30,9,outra
21,22,solteiro,ensino médio,NaN,11.59,34,2,capital
22,23,solteiro,ensino fundamental,NaN,12.00,41,0,outra
23,24,casado,superior,0.0,12.79,26,1,outra
24,25,casado,ensino médio,2.0,13.23,32,5,interior
25,26,casado,ensino médio,2.0,13.60,35,0,outra
26,27,solteiro,ensino fundamental,NaN,13.85,46,7,outra
27,28,casado,ensino médio,0.0,14.69,29,8,interior
28,29,casado,ensino médio,5.0,14.71,40,6,interior
29,30,casado,ensino médio,2.0,15.99,35,10,capital
30,31,solteiro,superior,NaN,16.22,31,5,outra
31,32,casado,ensino médio,1.0,16.61,36,4,interior
32,33,casado,superior,3.0,17.26,43,7,capital
33,34,solteiro,superior,NaN,18.75,33,7,capital
34,35,casado,ensino médio,2.0,19.40,48,11,capital
35,36,casado,superior,3.0,23.30,42,2,interior

# Montando a tabela para salário segundo a região de procedência.

In [4]:
# pego a frequência absoluta de cada valor
df['Região de Procedência'].value_counts()

Região de Procedência
outra       13
interior    12
capital     11
Name: count, dtype: int64

In [5]:
# pego a coluna de salário, agrupo por região de procedência e tiro a média do salário em cada grupo da região
media_regiao_procedencia = df['Salario (x Sal Min)'].groupby(df['Região de Procedência']).mean()
media_regiao_procedencia

Região de Procedência
capital     11.455455
interior    11.550000
outra       10.445385
Name: Salario (x Sal Min), dtype: float64

In [6]:
# pegar o desvio padrão desse agrupamento

df['Salario (x Sal Min)'].groupby(df['Região de Procedência']).std()

Região de Procedência
capital     5.476653
interior    5.296055
outra       3.145453
Name: Salario (x Sal Min), dtype: float64

In [7]:
# pegar a variância desse agrupamento:

var_procedencia = df['Salario (x Sal Min)'].groupby(df['Região de Procedência']).var(ddof=0)
print(var_procedencia)

Região de Procedência
capital     27.267025
interior    25.710850
outra        9.132809
Name: Salario (x Sal Min), dtype: float64

In [8]:
# visualizar média de salário:

print(df['Salario (x Sal Min)'].mean())

# visualizar desvio padrão de salário:

print(df['Salario (x Sal Min)'].std())

# visualizar variância de salário:

print(df['Salario (x Sal Min)'].var())

11.122222222222222
4.587457503803861
21.044766349206352

In [9]:
# montar a tabela de contigência:

# itens da tabela

regiao_procedencia = {'capital':11, 'interior':12, 'outra':13}
print(regiao_procedencia)
media_procedencia = {'capital': media_regiao_procedencia[0], 'interior': media_regiao_procedencia[1], 'outra': media_regiao_procedencia[2]}
print(media_procedencia)
std_procedencia = {'capital': 5.476653, 'interior': 5.296055, 'outra' : 3.145453}
print(std_procedencia)
var_procedencia = {'capital': var_procedencia[0], 'interior': var_procedencia[1], 'outra' : var_procedencia[2]}
print(var_procedencia)

{'capital': 11, 'interior': 12, 'outra': 13}
{'capital': 11.455454545454545, 'interior': 11.549999999999999, 'outra': 10.445384615384615}
{'capital': 5.476653, 'interior': 5.296055, 'outra': 3.145453}
{'capital': 27.267024793388433, 'interior': 25.710849999999997, 'outra': 9.132809467455619}

In [10]:
df_tabela = pd.DataFrame({
          'Região' : regiao_procedencia,
          'Média' : media_procedencia,
          'Desvio Padrão' : std_procedencia,
          'Variância' : var_procedencia

})

Total = [36, 11.1222, 4.5874, 21.0447]
df_tabela.loc['Total'] = Total
print(df_tabela)

          Região      Média  Desvio Padrão  Variância
capital     11.0  11.455455       5.476653  27.267025
interior    12.0  11.550000       5.296055  25.710850
outra       13.0  10.445385       3.145453   9.132809
Total       36.0  11.122200       4.587400  21.044700

In [11]:

# adicionando o N  à tabela:
regiao_procedencia = ['capital', 'interior', 'outra']
N = [11, 12, 13]
media = [11.455455, 11.550000, 10.445385]
std = [5.476653, 5.296055, 3.145453]
var = [27.267025, 25.710850, 9.132809]

df_tabela_2 = pd.DataFrame({
          'Região' : regiao_procedencia,
          'N' : N,
          'Média' : media,
          'Desvio Padrão' : std,
          'Variância' : var


})

print(df_tabela_2)

     Região   N      Média  Desvio Padrão  Variância
0   capital  11  11.455455       5.476653  27.267025
1  interior  12  11.550000       5.296055  25.710850
2     outra  13  10.445385       3.145453   9.132809

In [22]:
varInterna = 0 # variância interna, a soma com os pesos, da fórmula. Vou iniciar com zero para iterar depois.
# variância total, geral:

var_total = df['Salario (x Sal Min)'].var(ddof=0)

for N, Var in zip(df_tabela_2['N'], df_tabela_2['Variância']):
  varInterna = varInterna + N * Var

# é como se fosse a média ponderada da variância
Var_barra = varInterna / 36

# caĺculo do R2:
# 1 - (var_barra)/var_total
R2 = 1 - (Var_barra/var_total)
# visualização da variância total:
print(var_total)
# visualização da variância interna:
print(varInterna)
# visualização do R2:
print(R2)
# visualização da variância média (var barra):
print(Var_barra)

20.460189506172842
727.193992
0.012725023635933641
20.19983311111111

In [26]:
# cálculo do R2:

import statsmodels.api as sm
from statsmodels.formula.api import ols

modelo = ols('Q("Salario (x Sal Min)") ~ C(Q("Região de Procedência"))', data=df).fit()
r_sqaured = modelo.rsquared
print('Coeficente de determinação (R²):', r_sqaured)

Coeficente de determinação (R²): 0.012725018471166916

In [28]:
# CÁLCULO DO QUI_QUADRADO:

from scipy.stats import chi2_contingency

# Criar uma tabela de contingência a partir das colunas
contingency_table = pd.crosstab(df['Salario (x Sal Min)'], df['Região de Procedência'])

# Exibir a tabela de contingência
print(contingency_table)

# Realizar o teste qui-quadrado
chi2, p, dof, expected = chi2_contingency(contingency_table)

# Exibir os resultados
print(f"Qui-quadrado: {chi2}")
print(f"p-valor: {p}")
print(f"Graus de liberdade: {dof}")
print("Tabela esperada:")
print(expected)

Região de Procedência  capital  interior  outra
Salario (x Sal Min)
4.00                         0         1      0
4.56                         1         0      0
5.25                         1         0      0
5.73                         0         0      1
6.26                         0         0      1
6.66                         0         1      0
6.86                         0         1      0
7.39                         1         0      0
7.44                         0         0      1
7.59                         1         0      0
8.12                         0         1      0
8.46                         1         0      0
8.74                         0         0      1
8.95                         0         0      1
9.13                         0         1      0
9.35                         0         0      1
9.77                         1         0      0
9.80                         0         0      1
10.53                        0         1      0
10.76                        0         1      0
11.06                        0         0      1
11.59                        1         0      0
12.00                        0         0      1
12.79                        0         0      1
13.23                        0         1      0
13.60                        0         0      1
13.85                        0         0      1
14.69                        0         1      0
14.71                        0         1      0
15.99                        1         0      0
16.22                        0         0      1
16.61                        0         1      0
17.26                        1         0      0
18.75                        1         0      0
19.40                        1         0      0
23.30                        0         1      0
Qui-quadrado: 72.0
p-valor: 0.4114966835517727
Graus de liberdade: 70
Tabela esperada:
[[0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]
 [0.30555556 0.33333333 0.36111111]]